Administração de Usuarios
noharm-ai/frontend pull request #127
Opened 2021-11-16 16:37 UTC by GAntonyP

2021-11-17 00:23 UTC, marceloarocha requested changes
De modo geral, o código está ótimo.
A maior parte dos comentários dizem respeito às traduções que devem ser feitas.

Aguardo os ajustes.

2021-11-17 00:23 UTC, marceloarocha commented on src/components/Forms/User/index.jsx
> +
Usar referência pro arquivo de tradução para todas as mensagens acima.
Exemplo: https://github.com/noharm-ai/frontend/blob/develop/src/components/Forms/Intervention/index.jsx#L44

2021-11-17 00:23 UTC, marceloarocha commented on src/components/Forms/User/index.jsx
> +            className: 'gtm-bt-cancel-edit-exam'
alterar para gtm-bt-cancel-edit-user

2021-11-17 00:23 UTC, marceloarocha commented on src/components/Icon/svgs/index.jsx
> +//export { ReactComponent as userAdmin } from './userAdmin.svg';
Se essa linha não é necessária, pode removê-la.

2021-11-17 00:23 UTC, marceloarocha commented on src/components/UserAdmin/User/columns.jsx
> +          </Tooltip>
Usar referência pro arquivo de tradução em todos os textos do arquivo.

2021-11-17 00:23 UTC, marceloarocha commented on src/components/UserAdmin/feedback.jsx
> +export default function feedback(status, { nameSegment }) {
Este arquivo inteiro não faz sentido. Onde ele é utilizado?

2021-11-17 00:23 UTC, marceloarocha commented on src/components/UserAdmin/index.css
> +.row-dragging .drag-visible {
Estes estilos são específicos para tabelas onde existe ordenação manual de registros (arrastar linhas para cima ou para baixo). Este recurso é necessário na tabela de usuários? Não entendi a necessidade.

2021-11-17 00:23 UTC, marceloarocha commented on src/components/UserAdmin/User/columns.jsx
> +  }
Acredito que a funcionalidade de ordenação manual dos registros não é utilizada nesta tabela. Por isto, a coluna "Ordenar" não faz sentido aqui.

2021-11-17 00:23 UTC, marceloarocha commented on src/components/UserAdmin/index.jsx
> +      });
Usar referência pro arquivo de tradução.

2021-11-17 00:23 UTC, marceloarocha commented on src/components/UserAdmin/index.jsx
> +    console.log('showUserModal', data);
log não deve ser comitado

2021-11-17 00:23 UTC, marceloarocha commented on src/components/UserAdmin/index.jsx
> +          <Icon type="plus" /> Adicionar
Usar referência pro arquivo de tradução.

2021-11-17 00:23 UTC, marceloarocha commented on src/components/UserAdmin/index.jsx
> +        okType="primary gtm-bt-save-exam"
alterar para gtm-bt-save-user

2021-11-17 00:23 UTC, marceloarocha commented on src/components/UserAdmin/index.jsx
> +        cancelText="Cancelar"
Usar referência pro arquivo de tradução.

2021-11-17 00:23 UTC, marceloarocha commented on src/components/UserAdmin/index.jsx
> +import { add } from 'lodash';
Esta função não está sendo utilizada. Portanto pode ser removida.

2021-11-17 00:23 UTC, marceloarocha commented on src/translations/pt.json
> +    "warning": "Ao alterar o email a senha será redefinida"
Criar um novo atributo para este aviso:
`
"userAdmin": {
  "passwordResetWarning": "Ao alterar o email a senha será redefinida"
}
`

2021-11-17 00:23 UTC, marceloarocha commented on .env.sample
> -REACT_APP_API_URL=http://localhost:5000
Este arquivo não deve ser deletado.

2021-11-24 21:33 UTC, marceloarocha requested changes
Mais alguns ajustes ;)

2021-11-24 21:33 UTC, marceloarocha commented on src/components/Forms/User/index.jsx
> +      .required(t('Você se esqueceu de inserir o seu email.'))
utilizar referência para o arquivo de tradução.

2021-11-24 21:33 UTC, marceloarocha commented on src/store/ducks/userAdmin/index.js
> +  //firstFilter,
se nao vai ser utilizado, pode ser removido

2021-11-24 21:33 UTC, marceloarocha commented on src/store/ducks/userAdmin/index.js
> +const userAdd = (state = INITIAL_STATE, { user }) => ({
esta função não está mais sendo utilizada. pode remover.

2021-11-24 21:33 UTC, marceloarocha commented on src/store/ducks/userAdmin/index.js
> +  [Types.USERS_USER_ADD]: userAdd,
userAdd não está mais sendo utilizado. pode remover

2021-11-24 21:33 UTC, marceloarocha commented on src/translations/en.json
> +
Não faz sentido colocar essas mensagens dentro de "clinicalNotesIndicator". Mover para o atributo "userAdminForm"

2021-11-24 21:33 UTC, marceloarocha commented on src/translations/pt.json
> +    "errorDescription": "Aconteceu algo que nos impediu de salvar os dados deste usuário. Por favor, tente novamente"
Não faz sentido colocar essas mensagens dentro de "clinicalNotesIndicator". Mover para o atributo "userAdminForm"

2021-11-30 01:58 UTC, marceloarocha requested changes
Quase lá

2021-11-30 01:58 UTC, marceloarocha commented on src/components/Forms/User/index.jsx
> +      console.log("error", error)
remover console.log

2021-11-30 01:58 UTC, marceloarocha commented on src/translations/pt.json
> +    "invalidUser": "Usuário teste"
usuário teste? o que é isso?

2021-11-30 01:58 UTC, marceloarocha commented on src/translations/en.json
> +    "errorDescription": "Something happened that didn't prevent this user's data from being saved. Please try again",
Something prevented this user's data from being saved. Please try again.

2021-12-06 19:26 UTC, GAntonyP commented on src/translations/pt.json
> +    "invalidUser": "Usuário teste"
Fiz pra testar, esqueci de remover...

2021-12-21 08:35 UTC, merged